id: IF3AEAA57
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:51:32+00:00'
last_modified: '2022-06-08T16:19:09.001572+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22347
  title: མདོ་སྡུད་པ་དང་བཟང་སྤྱོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    789C:
      image_group_id: I1KG22367
      title: ''
      total_pages: 202
      order: 1
      base_file: 789C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
